server:
  port: 8080

spring:
  profiles:
    active: local # 디폴트 환경
  # 다국어 지원
  messages:
    basename: i18n/exception
    encoding: UTF-8
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # DB
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate.hbm2ddl.auto: none
    showSql: true
  # security
  jwt:
    secret: govlepel@$
